### ISSUE TITLE
Liquid Saffire 56 "Optical interface mode not found for value 3"

### ISSUE THREAD

**Issue by orinonakani** [alsa-project/snd-firewire-ctl-services#140]
Hi Takashi,

I'm very sorry to waste your time, but I'm new at this. I was able to get all of the dependencies, compile everything, and install `snd-dice-ctl-service`, but when I go to run the file, I get this error:
```
$ cargo run --bin snd-dice-ctl-service
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/snd-dice-ctl-service`
target/debug/snd-dice-ctl-service: error while loading shared libraries: libhitaki.so.0: cannot open shared object file: No such file or directory
```

Do you know what I'm doing wrong?

Sorry again for the trouble. Thank you in advance.

**Comment by orinonakani** [comment]
I ended up getting the shared libraries error fixed thanks to #65 , but now I get this error message:

```
$ cargo run --bin snd-dice-ctl-service 2
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/snd-dice-ctl-service 2`
Unknown domain error: , Optical interface mode not found for value 3

```

**Comment by takaswie** [comment]
Hi,

> I ended up getting the shared libraries error fixed thanks to #65 , but now I get this error message:
> 
> ```
> $ cargo run --bin snd-dice-ctl-service 2
>     Finished dev [unoptimized + debuginfo] target(s) in 0.12s
>      Running `target/debug/snd-dice-ctl-service 2`
> Unknown domain error: , Optical interface mode not found for value 3
> ```

Thanks for the report. The message should come from `deserialize_optical_out_iface_mode()` in `protocols/dice/src/focusrite.rs`. I expect you use either Focusrite Saffire 40 or Liquid Saffire 56. Would I ask you which device to use?

**Comment by orinonakani** [comment]
Thanks for your reply.

I'm using a Liquid Saffire 56.

I had a look at `protocols/dice/src/focusrite.rs`. I'm not great at code, but it seems the error is related to ADAT? I unplugged my ADAT preamp from the Saffire and reset it just to check, but I'm getting the same `Unknown domain error: , Optical interface mode not found for value 3` error.

**Comment by takaswie** [comment]
> I'm using a Liquid Saffire 56.
> 
> I had a look at `protocols/dice/src/focusrite.rs`. I'm not great at code, but it seems the error is related to ADAT? I unplugged my ADAT preamp from the Saffire and reset it just to check, but I'm getting the same `Unknown domain error: , Optical interface mode not found for value 3` error.

Thanks. The value is relevant to the configuration that the type of signal is used for the optical input/output interface.
We can select one of:

 * ADAT
 * S/PDIF (so called TOSLINK)
 * AES/EBU

The service program expects one of 0x00 (ADAT), 0x01(S/PDIF), and 0x02(AES/EBU) in register on your hardware for
the configuration, but actually it is 0x03. Then  it reports the error.

As a quick glance, there seems to be programming mistake. Would I ask you to apply below patch in your local code
and test again on behalf of me? I have Focusrite Liquid Saffire 56 as test device, but it is in my garage...

```
diff --git a/protocols/dice/src/focusrite.rs b/protocols/dice/src/focusrite.rs
index 20fbb49c..6240905f 100644
--- a/protocols/dice/src/focusrite.rs
+++ b/protocols/dice/src/focusrite.rs
@@ -724,7 +724,7 @@ impl<O: TcatExtensionOperation + SaffireproIoParamsSpecification>
             req,
             node,
             &sections.application,
-            IO_PARAMS_SIZE,
+            IO_PARAMS_OFFSET,
             &mut raw,
             timeout_ms,
         )?;
```

Cheers

**Comment by orinonakani** [comment]
Thanks for the explanation.

I won't be at my computer again until tomorrow morning, but I'll try the
patch then, sure. I'll let you know then what happens.

**Comment by orinonakani** [comment]
Sorry for the delay.

Just for clarification, (I'm a beginner at Git), that Git Diff output means I should change line 727 from `IO_PARAMS_SIZE,` to `IO_PARAMS_OFFSET,` right?

I tried, and the program doesn't give me an error anymore, but nothing happens when I execute it.

**Comment by takaswie** [comment]
Hi,

> Just for clarification, (I'm a beginner at Git), that Git Diff output means I should change line 727 from `IO_PARAMS_SIZE,` to `IO_PARAMS_OFFSET,` right?

Exactly.

> I tried, and the program doesn't give me an error anymore,

Great. I pushed the fix:

https://github.com/alsa-project/snd-firewire-ctl-services/commit/a354bb5b6276169dbcbcdbf5c2855cc180b3ddff

> but nothing happens when I execute it.

Yes. It"s service program, server in short. You need to use sort of user interface to communicate to the server.
For this purpose, I recommend to use `qashctl` in [qastools](https://gitlab.com/sebholt/qastools).

When executing the server with `-ldebug` command line option, you can see output from the server.

Cheers

**Comment by takaswie** [comment]
Besides, would I ask you to change the title of issue so that the other user can easily recognize the issue.

**Comment by orinonakani** [comment]
Thanks so much for your help. I'll try out qastools. Glad I could help you find a bug, too!
