### ISSUE TITLE
Many fragmented dependencies

### ISSUE THREAD

**Issue by zamaudio** [alsa-project/snd-firewire-ctl-services#177]
Hi,

I am on AVLinux which is a custom rolled debian flavour of GNU/Linux, which has a large user base for pro-audio.
I cannot install the required core dependency stack for this mixer software because its on an outdated version of Debian (and all the deps are very new).  It's a lot of work to compile this project from source:
First you need to get glib from the repo, gobject-introspection isn't detected even when installed,
then you need to compile libhitaki and libhinawa etc etc.

My main qualm with this project is that the dependencies are very fragmented, when all I really need is a CLI binary
that controls my firewire mixer.
Would it be possible to statically compile a binary and add it to the release so users can just grab this if they just want to use it standalone?

Thanks,

**Comment by takaswie** [comment]
> all I really need is a CLI binary that controls my firewire mixer.

The included service programs are not what you say. Read:

https://lore.kernel.org/alsa-devel/20230419084401.GA659018@workstation/

Please develop what you need by your own.

Regards

**Comment by takaswie** [comment]
Some ITPs had been accepted in Debian project for the libraries on which this software depends, see:

* https://github.com/alsa-project/snd-firewire-ctl-services/commit/ea780da8753a
