### ISSUE TITLE
After Linux-rt upgrade: Duet 2 not discovered by aplay

### ISSUE THREAD

**Issue by TeamB12** [alsa-project/snd-firewire-ctl-services#189]
The alsa stack seemed stable the last months and years til last week.
Artix Linux here, I upgraded from Linux 6.7-rt  to 6.10-rt and now it seems, the Duet2 Firewire is not discovered allways by aplay -l
The Tascam FW-1884 is somehow most of the times, still discovered.
This is strange because the Duet2 firewire is more stable and producing less xruns then the Tascam.
I ve tried different Firewire host controller - this does not help.
It does not seem to make the problem, but all my firewire audio interfaces are connected to an OWC thunderbolt dock that is official supported only for the OSX operating system.
But it does not make much problems, so I don think this is the problem.
I think it is the alsa module that came with the latest linux 6.10-rt kernel that is making problems now, so I am writing here - maybe this is the wrong place, then maybe you can show me the right direction.The dock is fully working except powering my laptop which has probably something to do with the laptop and not with the Dock.
Since the new 6.10-rt kernel the poweroff is quite often hanging in the last stage:
sending the killing term signal is hanging and freezing locking the system - only pushing the acpi power button for more then 5 seconds is powering off the system then emediatly.
I ve tried different Firewire Host controllers and I could see, that at one point, the Tascam was not connected anymore it was still listed when prompting aplay -l.
I am writing here because I dontknow where else to ask for help.
Duet is discovered in 1 of ten tries - the Tascam is discovered 9 of 10 times.
Using 2 different Firewire host controller here, both seem to produce the same results, so it is not about the Firewire host controller, I guess.
My solution now is changing to the vanilla kernel and waiting til the realtime patchset is fully merged into te mainlinekernel which hopefully will happen this year.
thanks for your work and your support.

**Comment by TeamB12** [comment]
Thank You again for pointing me to the related bug report.
Maybe We should relax, the realtime patchset mainlinemerge will come soon, I hope it will come the next 3 months.
Maybe, I will install linux-rt-lts  to see if the problem is still there.
Should I close this issue here?

**Comment by takaswie** [comment]
> Should I close this issue here?

Yes. It has no direct relationship to the control services provided by this repository.

**Comment by TeamB12** [comment]
Just two little infos, then I am closing this "issue":
1.) when prompting rtirq start, then I can see one to five IRQSs thatare getting priorized... one to five...this is strange...random process
2.)  When prompting aplay -l the numbers sequence changes a little after each restart, too.  also the count of the deiscovered alsa devies is changer from four to seven.
Closing this issue but keeping my eyes open.

**Comment by TeamB12** [comment]
see last comment, closing now.
