### ISSUE TITLE
Apogee Duet Firewire not discovered by latest kernel

### ISSUE THREAD

**Issue by TeamB12** [alsa-project/snd-firewire-ctl-services#191]
Artix Linux with latest kerne. 6.11 and openbox - no pipewire, only apulse - jack1 installed.
Everything is working great, also the firewire control is working great - thanks again.
Sometimes, which is almost always on the latest 6.11 kernel, the Duet is not discovered by aplay -l.
Sometimes (very rarely) it is not powered on ( no LEd, no clicking of the device)
The problem exists with the latest Linux and Linux-rt kernel.
Older LTS kernel like 6.6 -rt-LTS an d 6.6 LTS are allways discovering the Duet audio interface.
My workaround: boot into linux-rt-lts 6.6 kernel and then reboot into the latest 6.11 kernel and then my apogee duet is discovered by aplay -l
If i am trying to boot into latest kernel directly, the probablity of the Duet being disconvered is maybe 15%.
What was changed in kernel 6.10 so that my audio interface is not recognized anymore?
Tried different firewire host controllers like the apple thunderbolt  and an OWC dock with firewire 800 host interface - both the same results.
Are you aware of this regression?

**Comment by takaswie** [comment]
Hi @TeamB12 ,

The issue looks some problems in kernel stuffs. Please file it in https://github.com/takaswie/linux-firewire-dkms/ instead of this project for user space application.
