### ISSUE TITLE
efw: Mute control are inverse and more.

### ISSUE THREAD

**Issue by ovenwerks** [alsa-project/snd-firewire-ctl-services#3]
Testing with an audiofire 12. Wow lots of controls very hard to figure out which control goes where. Also impeded by not understanding ffado-mixer well. In order to see a change made by alsamixer in ffado-mixer, the "Refresh Current Panels" menu item has to be selected. In any case once I figured that out, I started testing with "Front" which really should be just 1 and 2 or 1/2. But before I got there, my AF12 defaults to wordclock and I have been having to boot with snd-fire* blacklist (modprobe -r doesn't seem to work)  just so I could switch to internal. This alone is worth all of it. However, I turn the AF12 on, then run snd-firewire-ctl-services, then alsamixer. It shows wordclock, the af12 front panel shows wordclock. So I use alsamixer to switch to internal but the device front panel still shows wordclock. So then I switch it to wordclock in alsamixer at which point the front panel of the device shows internal. And jack runs without the panel flashing. I am guessing that the device when it gets a switch to wordclock and there is no signal, aborts to internal but I do not why I can not just set it to internal.

 - Input Meter  and midi detect work so long as the "Monitoring" switch is turned on.
 - Mutes seem to be backwards in alsamixer where double MM means sound goes through rather than Mute. However, qasmixer has checked boxes on for muted, so I don't know where the bug(s) are in that. Ahh, I think this may be alsamixer which takes "off" to mean audio off rather than mute off. Most alsa cards use channel off for mute.
 - The level controls seem to work ok
 - pans seem to work more like a balance, not a pan though. (I expected my mono mic to be able to move from side to side, but it just got louder or quieter. (that may be the way the device works no fault of alsa)
 - solo works, mutes everything else and sends itself even if muted (that last is not standard but the way this one works)
 - The monitoring switch is the right way. On is on.
 - Calling the controls front, rear, center, woofer and side means that alsamixer only shows 8 out of 12 controls. Qasmixer has these names with numbers as well and when it runs out of names it uses ? number. If the wierd names need to remain, at least make the rest aux1-l/r, aux2l/r (they should really all be stereo pairs or all singles, but Echo's own GUI for windows/macos treats them as stereo pairs. Alsa is half and half with center and woofer being mono.

In all a gui like mudita24 has for the ICE1712 chip, would be great

**Comment by ovenwerks** [comment]
Further research shows that perhaps the Front, Rear, etc. naming is something alsamixer adds. sorry.

**Comment by takaswie** [comment]
Hi Len,

> Testing with an audiofire 12.

Thanks for your quick reaction and I apologize that the service program still includes bugs...

> Wow lots of controls very hard to figure out which control goes where. Also
> impeded by not understanding ffado-mixer well.

I also think it's not necessarily understandable. It includes 

> In order to see a change made by alsamixer in ffado-mixer, the
> "Refresh Current Panels" menu item has to be selected. In any case once I
> figured that out, I started testing with "Front" which really should be just
> 1 and 2 or 1/2.
>
> But before I got there, my AF12 defaults to wordclock and I have been having
> to boot with snd-fire* blacklist (modprobe -r doesn't seem to work) just so I
> could switch to internal. This alone is worth all of it. However, I turn the
> AF12 on, then run snd-firewire-ctl-services, then alsamixer. It shows
> wordclock, the af12 front panel shows wordclock. So I use alsamixer to switch
> to internal but the device front panel still shows wordclock. So then I
> switch it to wordclock in alsamixer at which point the front panel of the
> device shows internal. And jack runs without the panel flashing.
> I am guessing that the device when it gets a switch to wordclock and there is
> no signal, aborts to internal but I do not why I can not just set it to
> internal.

Thanks for your indication. It's a bug of the service program and I posted #4
and accumulate patches into `topic/service-for-efw` topic branch.

> * Input Meter and midi detect work so long as the "Monitoring" switch is turned on.

Yep. The 'monitoring' element is defined by the service program to start interval timer. In detail, please refer to picture labeled as 'Monitor model' in README webpage of the repository:
https://github.com/alsa-project/snd-firewire-ctl-services

However, the element name, `monitoring` is a bit confusing to actual `monitoring` functionality. I will investigate another name for it.

> * Mutes seem to be backwards in alsamixer where double MM means sound goes through rather than Mute. However, qasmixer has checked boxes on for muted, so I don't know where the bug(s) are in that. Ahh, I think this may be alsamixer which takes "off" to mean audio off rather than mute off. Most alsa cards use channel off for mute.

In my opinion, this is a quirk of smixer abstraction in alsa-lib. I don't got the mechanism yet..

> * The level controls seem to work ok
> * pans seem to work more like a balance, not a pan though. (I expected my mono mic to be able to move from side to side, but it just got louder or quieter. (that may be the way the device works no fault of alsa)

Oops. I did mistake to code pan command as the same as gain command, and I found the other bug to read current value of monitor. I posted #7 and #8 and pushed some patches to fix the bugs.

> * solo works, mutes everything else and sends itself even if muted (that last is not standard but the way this one works)
>* The monitoring switch is the right way. On is on.
>* Calling the controls front, rear, center, woofer and side means that alsamixer only shows 8 out of 12 controls. Qasmixer has these names with numbers as well and when it runs out of names it uses ? number. If the wierd names need to remain, at least make the rest aux1-l/r, aux2l/r (they should really all be stereo pairs or all singles, but Echo's own GUI for windows/macos treats them as stereo pairs. Alsa is half and half with center and woofer being mono.

The labels in alsamixer comes from smixer abstraction of alsa-lib. As long as I know, the abstraction is friendly with usual sound devices for stereo or usual surround channels. Apparently alsamixer needs to be improved for sound devices with multichannel.

Additionally, at present, ALSA control interface doesn't deliver name of channels from drivers (and services) to applications. I think this is not helpful and addressed to my RFT message.

> In all a gui like mudita24 has for the ICE1712 chip, would be great

Yep. However, my current focus is to implementing vendor-specific protocols for Audio and Music units on IEEE 1394 bus nad it's out of my scope for GUI application, sorry...

Anyway, thanks for your test ;)

**Comment by takaswie** [comment]
Fixed.
