### ISSUE TITLE
efw: clock source configuration is invalid

### ISSUE THREAD

**Issue by takaswie** [alsa-project/snd-firewire-ctl-services#4]
@ovenwerks reports at #3 with his Audiofire 12.

In ALSA control applications, change operation for clock source looks successful but the LEDs on device have no effect from the operation.

In 2a2bf6d010c7, the change operation is written below:

```
$ cat src/efw/clk_ctl.rs
    pub fn write(
        &mut self,
        unit: &hinawa::SndEfw,
        elem_id: &alsactl::ElemId,
        old: &alsactl::ElemValue,
        new: &alsactl::ElemValue,
    ) -> Result<bool, Error> {
        match elem_id.get_name().as_str() {
            Self::SRC_NAME => {
                if !unit.get_property_streaming() {
                    let mut vals = [0; 2];
                    old.get_enum(&mut vals[0..1]);
                    new.get_enum(&mut vals[1..]);
                    if vals[0] != vals[1] {
                        EfwHwCtl::set_clock(unit, Some(ClkSrc::from(vals[0] as usize)), None)?;
                    }
                    Ok(true)
                } else {
                    Ok(false)
                }
            }
            ...
            _ => Ok(false),
        }
    }
}
```

The old value is referred for the transaction. Furthermore, the value should be index in device specific table for supported clock source, but actually it's code in clock transaction.

**Comment by takaswie** [comment]
I accumulate three patches into `topic/service-for-efw` to fix the issue:

```
52b1b4a5 efw: fix failure to configure sampling rate
1515840d efw: fix failure to configure clock source
70041392 efw: simplify value handling for clock control elements
```

**Comment by takaswie** [comment]
Fix is pushed.

**Comment by ovenwerks** [comment]
Tested on audiofire12, Both clock-rate and clock-source now have immediate indication of change on the hardware LEDs.

**Comment by takaswie** [comment]
> Tested on audiofire12, Both clock-rate and clock-source now have immediate indication of change on the hardware LEDs.

Ok. Thanks for your test!
