### ISSUE TITLE
Fireface 802: Possibly overlooked mute-output option?

### ISSUE THREAD

**Issue by Schroedingers-Cat** [alsa-project/snd-firewire-ctl-services#47]
When muting an output channel via TotalMix FX on Windows and booting into Linux, the channel's output volume control in ALSA doesn't have any effect on the output volume of the muted channel and no audio is coming out of the output anymore.  
Booting into Windows and unmuting the channel in TotalMix FX makes ALSA's channel output volume control have an effect on the output again and audio send to that output actually comes out of the Fireface 802.

Since no mute-related parameter can be found in the alsa controls, I wonder if it has been overlooked and is something stored in the hardware's device state.

**Comment by takaswie** [comment]
Thanks for the report, and sorry for the inconvenience.

As long as reading packet dumps, I can not confirm such command for output mute.
You can see the list of command in:

https://github.com/alsa-project/snd-firewire-ctl-services/blob/master/protocols/fireface/src/latter.rs#L547

```
const OUTPUT_VOL_CMD: u8 = 0x00;
const OUTPUT_STEREO_BALANCE_CMD: u8 = 0x01;
const OUTPUT_FROM_FX_CMD: u8 = 0x03;
const OUTPUT_STEREO_LINK_CMD: u8 = 0x04;
const OUTPUT_INVERT_PHASE_CMD: u8 = 0x07;
const OUTPUT_LINE_LEVEL_CMD: u8 = 0x08;
```

I guess that the hardware lost routing between the channel in PCM frame and the headphone. You can configure it by `mixer:stream-source-gain`. The 8/9/10/11th mixer
corresponds to headphone output 0/1/2/3, then the channel 8/9/10/11 expresses the corresponding channel in PCM frame.

Regards

**Comment by takaswie** [comment]
Let me close the issue since expecting no reaction.

**Comment by Schroedingers-Cat** [comment]
https://github.com/alsa-project/snd-firewire-ctl-services/issues/44#issuecomment-1479348114
