### ISSUE TITLE
efw: +4/pad switches missing

### ISSUE THREAD

**Issue by ovenwerks** [alsa-project/snd-firewire-ctl-services#5]
There is a whole other set of controls which ffado-mixer calls "Pad" but the Windows GUI calls "+4" that are missing. I think calling them +4 (or maybe -10) is better because the outputs work opposite to the inputs. That is, for inputs, turning this on in ffado-mixer makes the input level go up (that would seem to indicate on is for -10 signals). For outputs, turning this on makes the the level go down so again -10. The values from the device may say pro/consumer, Pro devices run at +4 while consumer devices run at -10.
The input switches would be more important that the output switches as a large input could overload the analog portion of the preamp. The pad to set inputs to +4 mode should be passive and come before the preamp. (not saying I know this is true in fact, the delta series cards just set the input/output levels differently (at least the D44/66)

**Comment by takaswie** [comment]
Mmm. I program control elements (`input-nominal` and `output-nominal`) in below files:
 * src/efw/input_ctl.rs
 * src/efw/output_ctl.rs

But they are not added even if the target device supports them. I need more time to investigate further.

**Comment by takaswie** [comment]
> There is a whole other set of controls which ffado-mixer calls "Pad" but
> the Windows GUI calls "+4" that are missing. I think calling them +4
> (or maybe -10) is better because the outputs work opposite to the inputs.
> That is, for inputs, turning this on in ffado-mixer makes the input level
> go up (that would seem to indicate on is for -10 signals). For outputs,
> turning this on makes the the level go down so again -10. The values from
> the device may say pro/consumer, Pro devices run at +4 while consumer
> devices run at -10.
> The input switches would be more important that the output switches as a
> large input could overload the analog portion of the preamp. The pad to
> set inputs to +4 mode should be passive and come before the preamp. (not
> saying I know this is true in fact, the delta series cards just set the
> input/output levels differently (at least the D44/66)

Ok. The 'Pad' for input is in a domain of attenuator as well as 'Dim' for output.
Let us use +4dBu/-10dBV since it represents nominal signal level for input/output
lines.

I pushed below commits over `service-for-efw` branch to fix the issue:

```
fe8dd006 efw: cache current states of nominal input level for FPGA model
fa92005c efw: restrict to +4dBu/-10dBV for control element
c084710c efw: fixup nominal controls for AudioFire series
baf7622f efw: use hw_type field in hardware information to detect quirks
```

I'm happy if you test changes added by the above.

**Comment by takaswie** [comment]
Hi @ovenwerks ,

However, I find that three steps are used in Fireworks transaction for nominal level control. The step consists of the value between 0 and 2. The +4dBu corresponds to value 0 and the -10dBV corresponds to 2. In short:

* 0: +4dBu
* 1: ?
* 2: -10dBV

In current implementation:
https://github.com/alsa-project/snd-firewire-ctl-services/blob/topic/service-for-efw/src/efw/transactions.rs#L416

I have no idea for the medium state between +4dBu and -10dBV. Do you know something about it in the other devices or DAWs?

I program that +4dBu and -10dBV are only available for ALSA control applications.

**Comment by ovenwerks** [comment]
The Manufacture's Manual states: "You can switch between +4dBu (professional level) and –10dBV (consumer level) for each analog output and input by clicking on the appropriate button." So while there are some countries that use a 0dBu standard (or have in the past), I would hesitate to assume that 1 would give that level. I think it is reasonable to offer the same options as windows/mac controllers do.

**Comment by ovenwerks** [comment]
The Nominal control for channel one in and out both work as expected

**Comment by takaswie** [comment]
> The Nominal control for channel one in and out both work as expected

Ok. Let me close this issue. Thanks!
