### ISSUE TITLE
efw: Missing "Gang" switches

### ISSUE THREAD

**Issue by ovenwerks** [alsa-project/snd-firewire-ctl-services#6]
The ffado-mixer does not show these either, but using things like ffado-test does. The Windows GUI also shows gang switches across each pair of channels. I suspect that this is the reason the pan controls act like balance controls rather than pan controls. I will note that when using the ffado drivers, the pan controls do work as expected. So the gang switches seem to be set by default in the alsa driver. For the kind of mixing this internal mixer is made to be used for, mono inputs to stereo outputs would make more sense at least for control room monitoring but for performer personal monitoring mono outs would be useful too. So being able to switch each one would be helpful. Perhaps a better method is to set no groups as balance can be effected with changing left/right levels. So I don't know if this is a bug with this software or the snd-fireworks kernel module.

**Comment by takaswie** [comment]
In Fireworks transaction, operations for each channel is independent, thus the feature `gang` is purely implemented in software side (= GUI). At present, I don't support it in the service program.

However, even if being independent, pan operations to channels in a stereo pair are corresponding. For example, when operating pan control to channel 3, it has an effect to channel 4 implicitly. At present, the service program cannot catch the implicit effect. Mmm...

**Comment by ovenwerks** [comment]
If this is a software feature, then it is really not needed. My concern was that if it was internal to the audio device, it may get "stuck" in a setting that might make one of more channels less useful. I was probably confused by the term Groups that shows up in ffado-test Discover.

**Comment by takaswie** [comment]
> My concern was that if it was internal to the audio device, it may get "stuck" in a setting that might make one of more channels less useful.

Yep. If I were you, I might have the same concern ;) b

> I was probably confused by the term Groups that shows up in ffado-test Discover.

The 'Group' is a part of hardware information retrieved from the device. They represent the type of channel in monitor or playback. In the case of AudioFire 12, monitor has 12 channels for `Analog` input and playback has 12 channels for `Analog` output.

If you're interested, please refer to `struct HwInfo`, `struct PhysGroupEntry`, and `enum PhysGroupType` in  `src/efw/transaction.rs`:
https://github.com/alsa-project/snd-firewire-ctl-services/blob/topic/service-for-efw/src/efw/transactions.rs#L119

I'll keep this issue opened to consider about the pan control issue.

**Comment by takaswie** [comment]
> However, even if being independent, pan operations to channels in a stereo pair are corresponding. For example, when operating pan control to channel 3, it has an effect to channel 4 implicitly. At present, the service program cannot catch the implicit effect. Mmm...

Additionally I found that the same behaviour is seen for monitor-gain/monitor-mute/monitor-pan. These operations a channels have effects to the another channel in stereo pair.

**Comment by takaswie** [comment]
Let me close the issue since the feature purely depends on end-user software since
the communication with hardware includes such feature.
