### ISSUE TITLE
Can't run binary

### ISSUE THREAD

**Issue by zigol01** [alsa-project/snd-firewire-ctl-services#65]
When I try to launch `cargo run --bin snd-dice-ctl-service` I got this error:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.08s
     Running `/home/pszemo/programowanie/snd-firewire-ctl-services/target/debug/snd-dice-ctl-service`
/home/pszemo/programowanie/snd-firewire-ctl-services/target/debug/snd-dice-ctl-service: error while loading shared libraries: libalsaseq.so.0: cannot open shared object file: No such file or directory
```
How can I link libalsaseq so that main program would see it? I mean I checked and I have libalsaseq installed (`whereis libalsaseq`):
```
libalsaseq: /usr/local/lib/x86_64-linux-gnu/libalsaseq.so
```

**Comment by zigol01** [comment]
Ok I got this to work with that command: `sudo /sbin/ldconfig -v`
It probably generated all symbolic links to all libraries in my system, but I'm not sure.

But how can I check what `CARD_ID` do I have to pass in?

**Comment by zigol01** [comment]
Okay I found that command: `lspci | grep -E -i "(1394|firewire)"`
And this is an output:
```
05:04.0 FireWire (IEEE 1394): Texas Instruments TSB43AB23 IEEE-1394a-2000 Controller (PHY/Link)
```
So my systems sees my audio interface. I think that's a good sign.
Also there's that command: `lsmod | grep -E -i "(1394|firewire)"`
Which prints out this:
```
snd_firewire_lib       45056  1 snd_dice
snd_pcm               114688  13 snd_hda_codec_hdmi,snd_hda_intel,snd_firewire_lib,snd_usb_audio,snd_hda_codec,soundwire_intel,snd_compress,snd_soc_core,snd_hda_core,snd_dice,snd_pcm_dmaengine
snd_rawmidi            36864  4 snd_seq_midi,snd_firewire_lib,snd_usbmidi_lib,snd_dice
firewire_ohci          45056  0
firewire_core          65536  3 snd_firewire_lib,firewire_ohci,snd_dice
crc_itu_t              16384  1 firewire_core
```
But I'm not sure what number to choose from that... or maybe it is all wrong.

**Comment by takaswie** [comment]
You can see the card number in dump of `/proc/asound/cards`.

For my information, what model based on dice would you use?

**Comment by zigol01** [comment]
I can't find my Lexicon I-ONIX FW810s in `/proc/asound/cards`...

As mentioned earlier my system sees that the interface is connected through PCI card, but I don't see it in here (`cat /proc/asound/cards`):

```
 0 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xdf440000 irq 150
 1 [Webcam         ]: USB-Audio - C922 Pro Stream Webcam
                      C922 Pro Stream Webcam at usb-0000:00:14.0-1, high speed
 2 [NVidia         ]: HDA-Intel - HDA NVidia
                      HDA NVidia at 0xdf080000 irq 17

```
Is it so that without my interface showing inside cards list I can't manage to use it?

**Comment by zigol01** [comment]
Oh and also I would mention that it is connected through firewire to PCI card and if I'm running on Windows the blue LED pops up which, logically, if I don't have drivers for linux it's stays off.

**Comment by takaswie** [comment]
> I can't find my Lexicon I-ONIX FW810s in /proc/asound/cards...

The support of Lexicon I-ONIX FW810s was firstly added to ALSA dice driver in Linux kernel v5.12.

 * https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=9a08676fc5968be8575ee2fa8926e55d8aef166c

Unless the driver can detect your unit, the service program in this repository doesn't run.

**Comment by takaswie** [comment]
Let me close the issue since no reactions have been posted since last message.
