### ISSUE TITLE
efw: monitor panning works like balance switch

### ISSUE THREAD

**Issue by takaswie** [alsa-project/snd-firewire-ctl-services#7]
@ovenwerks reports at #3 with his Audiofire 12.

> pans seem to work more like a balance, not a pan though. (I expected my mono mic to be able to move from side to side, but it just got louder or quieter.

In 2a2bf6d010c7, implementation for Fireworks transaction has invalid command numbers for pan of monitor functionality. They are the same as solo.

```
pub struct EfwMonitor {}

impl EfwMonitor {
    const CMD_SET_VOL: u32 = 0;
    const CMD_GET_VOL: u32 = 1;
    const CMD_SET_MUTE: u32 = 2;
    const CMD_GET_MUTE: u32 = 3;
    const CMD_SET_SOLO: u32 = 4;
    const CMD_GET_SOLO: u32 = 5;
    const CMD_SET_PAN: u32 = 4;
    const CMD_GET_PAN: u32 = 5;

```

**Comment by takaswie** [comment]
I pushed a patch into `topic/service-for-efw` branch to fix the issue.

```
19aa2df7 efw: fix command number for pan control in mixer
```

**Comment by takaswie** [comment]
Fix is pushed.

**Comment by ovenwerks** [comment]
The pan controls now work as expected

**Comment by takaswie** [comment]
> The pan controls now work as expected

Good. Thanks for your report and patience!
