### ISSUE TITLE
Trouble Installing dependencies

### ISSUE THREAD

**Issue by cdd3** [alsa-project/snd-firewire-ctl-services#76]
Hello,
  Thank you for all your work on the firewire audio drivers!  

I have successfully installed the snd-firewire-improve drivers for my DIGI 002 Rack.  I have some success using the device with snd-firewire-improve but I am getting a lot of xruns and choppy audio when using with jack2.  I am now trying to build & install the snd-firewire-ctl-services as I hope that will help the device work better.  Part of my problem is that I do not have any previous experience with the rust language.  When I try to install the hinawa-rs and alsa-gobject-rs packages I get the following message:

$ cargo install --git https://github.com/alsa-project/hinawa-rs.git
    Updating git repository `https://github.com/alsa-project/hinawa-rs.git`
error: no packages found with binaries or examples

$ cargo install --git https://github.com/alsa-project/alsa-gobject-rs.git
    Updating git repository `https://github.com/alsa-project/alsa-gobject-rs.git`
error: no packages found with binaries or examples

thus when trying to build snd-firewire-ctl-services:

 $ cargo build
   Compiling hinawa-sys v0.4.0 (https://github.com/alsa-project/hinawa-rs.git?tag=v0.4.0#6865cfd3)
   Compiling alsatimer-sys v0.2.0 (https://github.com/alsa-project/alsa-gobject-rs.git?tag=v0.2.0#fcab3654)
error: failed to run custom build command for `hinawa-sys v0.4.0 (https://github.com/alsa-project/hinawa-rs.git?tag=v0.4.0#6865cfd3)`

Caused by:
  process didn't exit successfully: `/usr/local/src/snd-firewire-ctl-services/snd-firewire-ctl-services/target/debug/build/hinawa-sys-d6c0ffcaf03d9fbd/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=HINAWA_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=HINAWA_STATIC
  cargo:rerun-if-env-changed=HINAWA_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `"pkg-config" "--libs" "--cflags" "hinawa" "hinawa >= 2.3"` did not exit successfully: exit status: 1
  error: could not find system library 'hinawa' required by the 'hinawa-sys' crate

  --- stderr
  Package hinawa was not found in the pkg-config search path.
  Perhaps you should add the directory containing `hinawa.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'hinawa' found
  Package hinawa was not found in the pkg-config search path.
  Perhaps you should add the directory containing `hinawa.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'hinawa' found

warning: build failed, waiting for other jobs to finish...
error: build failed

If you can please offer me some guidance regarding how to resolve this error I would be very appreciative.

Thank you for your time.

-David

**Comment by takaswie** [comment]
Hi,

```
--- stderr
"pkg-config" "--libs" "--cflags" "hinawa" "hinawa >= 2.3" did not exit successfully: exit status: 1
error: could not find system library 'hinawa' required by the 'hinawa-sys' crate

--- stderr
```

As the error log, there is the lack of [libhinawa](https://github.com/alsa-project/libhinawa) libraryin your system. I note that libraries in [alsa-gobject](https://github.com/alsa-project/alsa-gobject/) are also required to be installed.

By the way, the service program in the project has neither effect to data streaming for audio frame
nor midi messages. Your trouble of jackd process seems to come from any configuration of the
process. I think it better to request advices to jackd users. You can see some reports from testers
of ALSA driver for digidesign digi 00x family in [the repository](https://github.com/takaswie/snd-firewire-improve/issues?q=is%3Aissue+is%3Aclosed+digidesign).

Regards

**Comment by takaswie** [comment]
Let me close it since getting no reactions last month.
