### ISSUE TITLE
Capacity of snd.ko 

### ISSUE THREAD

**Issue by wundermusiker** [alsa-project/snd-firewire-ctl-services#77]
Hello,

I am Linux Kernel:

Linux version 5.4.0-94-lowlatency (buildd@lcy02-amd64-053).

My Card is a Focusrite Saffire Pro 24 DSP Firewire, detected with cat /proc/asound/cards:

0 [Pro24DSP002245 ]: DICE - Pro24DSP-002245

Focusrite SAFFIRE_PRO_24DSP (serial 8773) at fw1.0, S400

I had no issue in building.

When executing: cargo run --bin snd-dice-ctl-service 0

I receive:

Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/snd-dice-ctl-service 0`
Allocation of user-defined element set reached capacity of snd.ko
This can be fixed by using Linux kernel v5.13 or later,
or by using snd.ko pached to extend the capacity.
The capacity is defined as 'MAX_USER_CONTROLS'located in 'sound/core/control.c'.
Fail to listen to events: ioctl(ELEM_ADD) 12(Cannot allocate memory)

Usage:
  snd-dice-ctl-service CARD_ID

  where
    CARD_ID: The numeric ID of sound card

How can I fix that?

**Comment by wundermusiker** [comment]
Stupid me. My mind told me 5.1.3 instead of 5.13.. Now it works.

Any chance to  get under alsamixer the enable/ disable buttons for compressor, equalizer, metering, reverb saturation to work?
 It is either on or MM stated. Setting the level or volume seems to work. Although I did not check if the settings are kept after reboot.

**Comment by takaswie** [comment]
Closed.
