### ISSUE TITLE
Focusrite Saffire Pro 24 DSP Issue Settings Alsamixer

### ISSUE THREAD

**Issue by wundermusiker** [alsa-project/snd-firewire-ctl-services#78]
Hello,

I cannot change some settings in Alsamixer.
1. compressor-attack  - value cannot be changed
2. compressor-enable - value cannot be changed (stuck at 0M (on))

3. equalizer-enable - value cannot be changed (stuck at MM (off))

4. metering -value cannot be changed (stuck at MM (off))

5. mixer-out-saturation - all 5 settings (front,back, etc.)- value cannot be changed (stuck at MM (off))

6. mixer-source-meter - all 5 settings (front,back, etc.)- value cannot be changed (stuck at 0<>0 )

7. output-source-meter - all 5 settings (front,back, etc.)- value cannot be changed (stuck at 0<>0 )

8. reverb-enable - value cannot be changed (stuck at MM (off))

9. stream-source-meter - all 5 settings (front,back, etc.)- value cannot be changed (stuck at 0<>0 )

Also not shure if that is correct, all on/off settings for compressor, reverb, equalizer etc. are on the play side only. They cannot be found on the record side in alsamixer.

regards

**Comment by takaswie** [comment]
Hi,

Thanks for the report.

> I cannot change some settings in Alsamixer.
> 
>     1. compressor-attack  - value cannot be changed
> 
>     2. compressor-enable - value cannot be changed (stuck at 0M (on))
> 
>     3. equalizer-enable - value cannot be changed (stuck at MM (off))
> 
>     4. metering -value cannot be changed (stuck at MM (off))
> 
>     5. mixer-out-saturation - all 5 settings (front,back, etc.)- value cannot be changed (stuck at MM (off))
> 
>     6. mixer-source-meter - all 5 settings (front,back, etc.)- value cannot be changed (stuck at 0<>0 )
> 
>     7. output-source-meter - all 5 settings (front,back, etc.)- value cannot be changed (stuck at 0<>0 )
> 
>     8. reverb-enable - value cannot be changed (stuck at MM (off))
> 
>     9. stream-source-meter - all 5 settings (front,back, etc.)- value cannot be changed (stuck at 0<>0 )
> 
> 
> Also not shure if that is correct, all on/off settings for compressor, reverb, equalizer etc. are on the play side only. They cannot be found on the record side in alsamixer.

I'm sorry to your inconvenience, however alsamixer has such disadvantage since it heavily relies on
alsa-lib's simple mixer API which includes many hard-coded rules. Therefore I recommend you to use
the other applications such as `quasmixer` in https://gitlab.com/sebholt/qastools.

I note that my investigation for channel strip effect of Saffire Pro 24 DSP is not completed yet. On the other hand,
the protocol implementation for reverv effect works well. I'd like you to glimpse source file for it:

https://github.com/alsa-project/snd-firewire-ctl-services/blob/master/libs/dice/protocols/src/focusrite/spro24dsp.rs

**Comment by wundermusiker** [comment]
Hello Takashi,

thanks for directing me to Qasmixer. Much better overview and easier to
handle.

You did an amazing job. First time I played around with the internal
reverb of my Focusrite.

So if you have any update I am happy to test.

If got a link for a routing table overview it would be great. It took my
a while to find the right settings to listen to the internal reverb in
my DAW:).

Again thank you very much.

**Comment by takaswie** [comment]
> Hello Takashi,
> 
> thanks for directing me to Qasmixer. Much better overview and easier to handle.
> 
> You did an amazing job. First time I played around with the internal reverb of my Focusrite.
> 
> So if you have any update I am happy to test.
> 
> If got a link for a routing table overview it would be great. It took my a while to find the right settings to listen to the internal reverb in my DAW:).
> 
> Again thank you very much.

Nice to hear it.

I think your experience is good to the other users. When you find such users, I'd like you to give
enough instructions to them as well.

Cheers.
