### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by sxiii** [alsa-project/snd-firewire-ctl-services#79]
Greetings! Trying to compile `snd-bebob-ctl-service` for M-Audio Project Mix I/O.

As far as I understood, it requires this one as well: https://github.com/alsa-project/alsa-gobject/
Tried installing alsa-gobject, after running `pkg-config --cflags --libs alsactl` getting this:

```
Package alsactl was not found in the pkg-config search path.
Perhaps you should add the directory containing `alsactl.pc'
to the PKG_CONFIG_PATH environment variable
Package 'alsactl', required by 'virtual:world', not found
```

<details><summary>Returning to snd-firewire-ctl-services, while trying "cargo build":</summary>

```
[s@asus-mainrig snd-firewire-ctl-services]$ cargo build
   Compiling hinawa-sys v0.4.0 (https://github.com/alsa-project/hinawa-rs.git?tag=v0.4.0#6865cfd3)
   Compiling alsatimer-sys v0.2.0 (https://github.com/alsa-project/alsa-gobject-rs.git?tag=v0.2.0#fcab3654)
   Compiling alsactl-sys v0.2.0 (https://github.com/alsa-project/alsa-gobject-rs.git?tag=v0.2.0#fcab3654)
error: failed to run custom build command for `alsatimer-sys v0.2.0 (https://github.com/alsa-project/alsa-gobject-rs.git?tag=v0.2.0#fcab3654)`

Caused by:
  process didn't exit successfully: `/home/s/sound/snd-firewire-ctl-services/target/debug/build/alsatimer-sys-58b1bd9cf56c052d/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=ALSATIMER_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=ALSATIMER_STATIC
  cargo:rerun-if-env-changed=ALSATIMER_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  `"pkg-config" "--libs" "--cflags" "alsatimer" "alsatimer >= 0.0"` did not exit successfully: exit status: 1
  error: could not find system library 'alsatimer' required by the 'alsatimer-sys' crate

  --- stderr
  Package alsatimer was not found in the pkg-config search path.
  Perhaps you should add the directory containing `alsatimer.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'alsatimer', required by 'virtual:world', not found
  Package 'alsatimer', required by 'virtual:world', not found

warning: build failed, waiting for other jobs to finish...
error: build failed
```

</details>

Also tried compiling and installing alsa-gobject-rs and libhinawa, and it does not help. Lastly, tried fiddling around with the `PKG_CONFIG_PATH=/usr/bin:/home/s/sound/alsa-gobject/build/meson-private/:/home/s/sound/libhinawa/build/meson-private/:/home/s/sound/alsa-gobject/build/meson-private/:/home/s/sound/alsa-gobject/build/meson-private/` etc. Does not work.

OS: Garuda Linux (arch-based) 
Kernel: 5.15.24-2-lts
Alsactl installed, exists and runs OK.

Any advice? Can't get audio output on the Project Mix, basically I just need to enable all audio outputs and pull the volume up, however, the ffado-mixer also does not work.

Thanks!

**Comment by takaswie** [comment]
Hi

> Greetings! Trying to compile `snd-bebob-ctl-service` for M-Audio Project Mix I/O.
> 
> As far as I understood, it requires this one as well: https://github.com/alsa-project/alsa-gobject/ Tried installing alsa-gobject, after running `pkg-config --cflags --libs alsactl` getting this:
> 
> ```
> Package alsactl was not found in the pkg-config search path.
> Perhaps you should add the directory containing `alsactl.pc'
> to the PKG_CONFIG_PATH environment variable
> Package 'alsactl', required by 'virtual:world', not found
> ```
> 
> Returning to snd-firewire-ctl-services, while trying "cargo build":
> Also tried compiling and installing alsa-gobject-rs and libhinawa, and it does not help. Lastly, tried fiddling around with the `PKG_CONFIG_PATH=/usr/bin:/home/s/sound/alsa-gobject/build/meson-private/:/home/s/sound/libhinawa/build/meson-private/:/home/s/sound/alsa-gobject/build/meson-private/:/home/s/sound/alsa-gobject/build/meson-private/` etc. Does not work.
> 
> OS: Garuda Linux (arch-based) Kernel: 5.15.24-2-lts Alsactl installed, exists and runs OK.

In the context, `alsactl` means `libalsactl.so` shared library installed from alsa-gobject.
It is not the one in [alsa-utils](https://github.com/alsa-project/alsa-utils).

When successfully installed, `alsactl.pc` can should be found under the path for pkg-config, therefore configuration of
your installation is not suitable to your system environment for pkg-config. The `alsactl.pc` is installed into the path unexpected
to your pkg-config runtime.

> Any advice?

Would you check pkg-config installation for *.pc files in your system, then seek the location of installed `alsactl.pc`?
If they are mismatch, you need to arrange your configuration for the installation.

> Can't get audio output on the Project Mix, basically I just need to enable all audio outputs and pull the volume up,

Indeed. At the initial state, Project Mix I/O has no routes between mixer sources and physical/stream inputs, thus
it generates silent audio from its physical outputs. We need to execute asynchronous write transaction of IEEE 1394 bus
to configure them. If you are interested, let's see https://github.com/alsa-project/snd-firewire-ctl-services/blob/master/libs/bebob/protocols/src/maudio/special.rs

Cheers.

**Comment by takaswie** [comment]
Let me close it since no reactions for several months.
