### ISSUE TITLE
How to install? 

### ISSUE THREAD

**Issue by francoisromain** [alsa-project/snd-firewire-ctl-services#85]
Hello, 
I am new to this. Sorry for my stupid questions. 

I just would like to install the firewire driver for the fireface 802 on ubuntu 22.04. 

I cloned this repo, then I installed the dependencies: 
- `rust` and `cargo`, 
- and with apt install: `libudev1`, `gobject-introspection`, `meson`,  `ninja-build`, `build-essential` and `libgtk2.0-dev`

Now I would like to install `libhinawa`, `libhitaki` and `alsa-gobject`. So I cloned the 3 repos to build them. But in the docs, I don't understand what are the `directory-to-install` and the `build-directory` variables. 

Could you explain how to do it please?

**Comment by takaswie** [comment]
Hi,

> But in the docs, I don't understand what are the directory-to-install and the build-directory variables.

It depends on system; e.g. Ubuntu in your case.

For Ubuntu distribution, I think it convenient to generate deb package by hand. Each repositories for `libhinawa`, `libhinoko`, and `alsa-gobject` has `topic/debian` branch.
You can generate the package by:

```
$ dpkg-buildpackage -rfakeroot -uc -b
```

At least, below 14 packages should be installed in your system:

 * libhinawa2_2.5.1-1_amd64.deb
 * libhitaki0_0.1.1-1_amd64.deb
 * libalsactl0_0.3.0_amd64.deb
 * libalsahwdep0_0.3.0_amd64.deb
 * libalsarawmidi0_0.3.0_amd64.deb
 * libalsaseq0_0.3.0_amd64.deb
 * libalsatimer0_0.3.0_amd64.deb

 * gir1.2-hinawa-3.0_2.5.1-1_amd64.deb
 * gir1.2-hitaki-0.0_0.1.1-1_amd64.deb
 * gir1.2-alsactl-0.0_0.3.0_amd64.deb
 * gir1.2-alsahwdep-0.0_0.3.0_amd64.deb
 * gir1.2-alsarawmidi-0.0_0.3.0_amd64.deb
 * gir1.2-alsaseq-0.0_0.3.0_amd64.deb
 * gir1.2-alsatimer-0.0_0.3.0_amd64.deb

P.S. `libgtk2.0-dev` package is not required since the software has no relationship to GUI framework.

When install the above packages, the software could be built in your local system
without any specific notice.

Cheers.

**Comment by francoisromain** [comment]
Thank you for your answer. 
I had to install missing dependendies `libudev-dev`, `libgirepository1.0-dev` and `gi-docgen`.
Then I generated the deb pakages for `alsa-gobject` and `libhitaki`. 

But `libhinawa` doesn't have a `topic/debian` branch, and I was not able to build the deb files for this one. How should I do it?

**Comment by dreamcat4** [comment]
@francoisromain thanks for this updated list of build dependancies for ubuntu 22.04. Very helpful, much appreciated.

> But libhinawa doesn't have a topic/debian branch, and I was not able to build the deb files for this one. How should I do it?

well... @takaswie is great so he probably will just update the git to fix that now that you have mentioned it

But in the meantime (if you cannot wait for that), then it should be possible manually build and install it onto your system with the following set of cmds:

```sh
# build lib
mkdir -p ~/.builds/firewire
cd ~/.builds/firewire
git clone https://github.com/alsa-project/libhinawa
cd libhinawa
meson --prefix=/usr build-directory
meson compile -C build-directory
meson test -C build-directory
sudo meson install -C build-directory

# build crate
mkdir -p ~/.builds/firewire
cd ~/.builds/firewire
git clone https://github.com/alsa-project/hinawa-rs.git
cd hinawa-rs
git submodule update --init --recursive
./generate.py
```

(or something like that, at least it worked for me with the recent v0.3x release)

**Comment by takaswie** [comment]
> But libhinawa doesn't have a topic/debian branch, and I was not able to build the deb files for this one. How should I do it?

Oops, indeed. I've never pushed the branch from my local repository to the remote repository since releases of libhinawa has already been in Debian/Ubuntu official repositories. I'm waiting for v2.5.1 packaging:

 * https://salsa.debian.org/debian/libhinawa/-/issues/21

For convenience, I pushed it now:

 * https://github.com/alsa-project/libhinawa/tree/topic/debian

I'm sorry to puzzle you.

**Comment by takaswie** [comment]
```
# build crate
mkdir -p ~/.builds/firewire
cd ~/.builds/firewire
git clone https://github.com/alsa-project/hinawa-rs.git
cd hinawa-rs
git submodule update --init --recursive
./generate.py
```

I note that the step is not required just to build the software since the software is configured
to pull git remote repositories for dependent Rust crates at present.

**Comment by takaswie** [comment]
Hi,

Today I finished relevant work for hinawa-rs/hitaki-rs/alsa-gobject-rs to depends on glib crate v0.15, and commit to master so that whole codes are based on them.

 * https://github.com/alsa-project/snd-firewire-ctl-services/pull/87

I updated README.rst to simplify dependency description. It's enough just to take care of
dependent C libraries since all of external crates are now available in crate.io.

Cheers.

**Comment by francoisromain** [comment]
Hello Takashi, 
Thank you for your help. 

I generated the deb files for libhinawa also. Then, I installed the 14 generated packes you listed above. 

example: 
```
❯ sudo apt install ./libhitaki0_0.1.1-1_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libhitaki0' instead of './libhitaki0_0.1.1-1_amd64.deb'
The following NEW packages will be installed:
  libhitaki0
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/20,4 kB of archives.
After this operation, 86,0 kB of additional disk space will be used.
Get:1 /home/fr/Desktop/alsa-deb/libhitaki0_0.1.1-1_amd64.deb libhitaki0 amd64 0.1.1-1 [20,4 kB]
Selecting previously unselected package libhitaki0:amd64.
(Reading database ... 234428 files and directories currently installed.)
Preparing to unpack .../libhitaki0_0.1.1-1_amd64.deb ...
Unpacking libhitaki0:amd64 (0.1.1-1) ...
Setting up libhitaki0:amd64 (0.1.1-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3) ...
N: Download is performed unsandboxed as root as file '/home/fr/Desktop/alsa-deb/libhitaki0_0.1.1-1_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
```

* * *

Now when I go back to the `snd-firewire-ctl-services` directory, git pull the updated content and run `cargo build`, it starts to build but then makes many errors like : `error: could not find system library 'hitaki' required by the 'hitaki-sys' crate`. 

What am i doing wrong here?

**Comment by dreamcat4** [comment]
btw also... not sure why you have `debian/` subfolder in its own seperate branches. it would be easier for others to build if it was just merged into the main branch

**Comment by takaswie** [comment]
> Now when I go back to the `snd-firewire-ctl-services` directory, git pull the updated content and run `cargo build`, it starts to build but then makes many errors like : `error: could not find system library 'hitaki' required by the 'hitaki-sys' crate`.

Oops, I forget that ll of the FFI crates (`*-sys`) check [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/) files provided by dependent libraries when being built. The build dependency has `*-dev` deb packages; e.g. `libhitaki-dev`, while I missed it in README.md...

Would I ask you to install generated `*-dev ` deb packages as well before building the software.

I'm sorry to use your time for the task like dogfooding... I should have added details into install section of README.

Cheers

**Comment by takaswie** [comment]
> btw also... not sure why you have `debian/` subfolder in its own seperate branches. it would be easier for others to build if it was just merged into the main branch

I intentionally split stuffs deb packaging for [ITP](https://wiki.debian.org/ITP).

**Comment by francoisromain** [comment]
Thank you again :). 

I already installed `libalsactl0_0.3.0_amd64.deb` and `libalsatimer0_0.3.0_amd64.deb` and still have 2 errors when doing `cargo build` from`snd-firewire-ctl-services` : 
- `error: could not find system library 'alsactl' required by the 'alsactl-sys' crate`
- `error: could not find system library 'alsatimer' required by the 'alsatimer-sys' crate`

**Comment by takaswie** [comment]
> I already installed `libalsactl0_0.3.0_amd64.deb` and `libalsatimer0_0.3.0_amd64.deb` and still have 2 errors when doing `cargo build` from`snd-firewire-ctl-services` :
> 
>     * `error: could not find system library 'alsactl' required by the 'alsactl-sys' crate`
> 
>     * `error: could not find system library 'alsatimer' required by the 'alsatimer-sys' crate`

It means that generated 'alsa-gobject-dev' package is not installed into your system. The package includes pkg-config files for all of included libraries such as libalsactl0 and libalsatimer0.

**Comment by francoisromain** [comment]
Ok it works! :smile: :partying_face: 

* * *
Here is a recap of the whole process to install a firewire driver on Ubuntu 22.04

1. Install rust and cargo. [Instructions](https://www.rust-lang.org/learn/get-started)

2. Install dependencies `sudo apt install libudev1 gobject-introspection meson ninja-build build-essential libudev-dev libgirepository1.0-dev gi-docgen`

3. Generate the deb packages for other dependencies [libhinawa](https://github.com/alsa-project/libhinawa), [libhitaki](https://github.com/alsa-project/libhitaki) and [alsa-gobject](https://github.com/alsa-project/alsa-gobject/)
  For each repo: 
    - clone the repo, fetch the remote branch `topic/debian` and checkout this branch.
    - generate the deb packages with `dpkg-buildpackage -rfakeroot -uc -b`

4. Install the generated deb packages for the additional dependencies  with `sudo apt install ./<package_name.deb>` for: 
    - `libhinawa2_2.5.1-1_amd64.deb`
    - `libhitaki0_0.1.1-1_amd64.deb`
    - `libalsactl0_0.3.0_amd64.deb`
    - `libalsahwdep0_0.3.0_amd64.deb`
    - `libalsarawmidi0_0.3.0_amd64.deb`
    - `libalsaseq0_0.3.0_amd64.deb`
    - `libalsatimer0_0.3.0_amd64.deb`
    - `gir1.2-hinawa-3.0_2.5.1-1_amd64.deb`
    - `gir1.2-hitaki-0.0_0.1.1-1_amd64.deb`
    - `gir1.2-alsactl-0.0_0.3.0_amd64.deb`
    - `gir1.2-alsahwdep-0.0_0.3.0_amd64.deb`
    - `gir1.2-alsarawmidi-0.0_0.3.0_amd64.deb`
    - `gir1.2-alsaseq-0.0_0.3.0_amd64.deb`
    - `gir1.2-alsatimer-0.0_0.3.0_amd64.deb`
    - `libhinawa-dev_2.5.1-1_amd64.deb`
    - `libhitaki-dev_0.1.1-1_amd64.deb`
    - `alsa-gobject-dev_0.3.0_amd64.deb`

5. Clone this repo [snd-firewire-ctl-services](https://github.com/alsa-project/snd-firewire-ctl-services)

6. Get the `card_id` of the firewire soundcard with `arecord -l`. In my case `card_id` is `4`.

7. Run the driver: `cargo run --bin <driver_name> <card_id>`. Ex: `cargo run --bin snd-fireface-ctl-service 4`

* * *

Thank you very much for your time making these drivers and for your help. 
(I would be happy to donate to support your work, if you have a way of doing that.)

I have 2 more questions for now : 
- how to handle the update on my computer when you update the drivers? 
- will this process eventually become easier, or is it the normal way to go?

You can close the issue. 
Thank you again.
:pray:

**Comment by takaswie** [comment]
Closed.

**Comment by mungewell** [comment]
Unfortunately I can not get 'gobject' to build a `.deb`. It errors and I don't understand why - perhaps wrong repo or missing dependancy?

```
simon@EliteBook:~$ git clone https://github.com/alsa-project/alsa-gobject.git alsa-gobject.github
Cloning into 'alsa-gobject.github'...
remote: Enumerating objects: 6462, done.
remote: Counting objects: 100% (2937/2937), done.
remote: Compressing objects: 100% (639/639), done.
remote: Total 6462 (delta 2462), reused 2556 (delta 2272), pack-reused 3525 (from 1)
Receiving objects: 100% (6462/6462), 966.19 KiB | 2.27 MiB/s, done.
Resolving deltas: 100% (5311/5311), done.

simon@EliteBook:~$ cd alsa-gobject.github/

simon@EliteBook:~/alsa-gobject.github$ git checkout topic/debian
branch 'topic/debian' set up to track 'origin/topic/debian'.
Switched to a new branch 'topic/debian'

simon@EliteBook:~/alsa-gobject.github$ git log | head
commit 083e6ce0d439fefcbc688069cca0f3f1f9c56317
Author: Takashi Sakamoto <o-takashi@sakamocchi.jp>
Date:   Thu Jun 9 17:36:18 2022 +0900

    debian: debian packaging for v0.3.0 release

commit 0c79385285f36d99fb2fce1eb65686a64f911da1
Author: Takashi Sakamoto <o-takashi@sakamocchi.jp>
Date:   Mon May 30 11:21:00 2022 +0900

simon@EliteBook:~/alsa-gobject.github$ dpkg-buildpackage -rfakeroot -uc -b
...
INFO: Creating OpenSearch file for ALSARawmidi-0.0: doc/rawmidi/alsarawmidi/opensearch.xml
INFO: Creating index file for ALSARawmidi-0.0: doc/rawmidi/alsarawmidi/index.json
INFO: Copying file /usr/lib/python3/dist-packages/gidocgen/templates/basic/style.css: doc/rawmidi/alsarawmidi/style.css
INFO: Copying file /usr/lib/python3/dist-packages/gidocgen/templates/basic/fonts.css: doc/rawmidi/alsarawmidi/fonts.css
INFO: Copying file /usr/lib/python3/dist-packages/gidocgen/templates/basic/fzy.js: doc/rawmidi/alsarawmidi/fzy.js
INFO: Copying file /usr/lib/python3/dist-packages/gidocgen/templates/basic/go-up-symbolic.png: doc/rawmidi/alsarawmidi/go-up-symbolic.png
INFO: Copying file /usr/lib/python3/dist-packages/gidocgen/templates/basic/main.js: doc/rawmidi/alsarawmidi/main.js
INFO: Copying file /usr/lib/python3/dist-packages/gidocgen/templates/basic/solarized-light.css: doc/rawmidi/alsarawmidi/solarized-light.css
INFO: Copying file /usr/lib/python3/dist-packages/gidocgen/templates/basic/solarized-dark.css: doc/rawmidi/alsarawmidi/solarized-dark.css
INFO: Copying file /usr/lib/python3/dist-packages/gidocgen/templates/basic/search.js: doc/rawmidi/alsarawmidi/search.js
INFO: Copying file /home/simon/alsa-gobject.github/doc/rawmidi/urlmap.js: doc/rawmidi/alsarawmidi/urlmap.js
ninja: build stopped: subcommand failed.
dh_auto_build: error: cd obj-x86_64-linux-gnu && LC_ALL=C.UTF-8 ninja -j4 -v returned exit code 1
make: *** [debian/rules:8: build] Error 1
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```

**Comment by takaswie** [comment]
Hi @mungewell ,

> WARNING: Section interfaces raised Invalid version: '0.3.'

I can regenerate this bug.

It is due to the behaviour change of gi-docgen 2023.3, and I've already solved it by https://github.com/alsa-project/alsa-gobject/pull/84. In the case of `topic/debian` remote branch, it is still based on the previous releases which does not include the fixes, while I am enough lazy to create new release of alsa-gobject to include the fix...

Anyway, it would be solved to rebase the branch onto current master remove branch. Please test it.

**Comment by takaswie** [comment]
@mungewell ,

In my opinion, the demand of `edition2024` would come from the updated version of [cfg-expr crate](https://crates.io/crates/cfg-expr). The simple operation to install the latest stable rust toolchain can not solve the issue.

```
Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.75.0).
```

It would be resolved when tell the version of cfg-expr crate to build environment, like:

```
$ cargo update -p cfg-expr --precise 0.18.0
$ cargo build
```

Let's try it.

**Comment by takaswie** [comment]
@mungewell 

Just now I made a new alsa-gobject release (v0.3.1), then rebase the `topic/debian` branch onto it and pushed. It is available instead of your local branch, I think.

Thanks
