### ISSUE TITLE
problem with cargo run - interferes with "rustup update"

### ISSUE THREAD

**Issue by dreamcat4** [alsa-project/snd-firewire-ctl-services#90]
Hi,
In the README instructions, the suggestion is to run the service via `cargo run` command

```sh
& cargo run --bin (the executable name) (the arguments of executable)
```

however i discovered today, that (while cargo run is running in the background). It keeps deleting a file called `rustup-init` in `~/.cargo/bin/`... and this breaks the rustup self update (or rustup update).

Not sure why this is happening. But here is the evidence...

```sh
θ68° [id:~] 255 $ sudo auditctl -w /home/id/.cargo/bin/rustup-init -p wra
[id:~] 1 $ ausearch -f /home/id/.cargo/bin/rustup-init -i
----
type=PROCTITLE msg=audit(20/07/22 15:23:37.098:305) : proctitle=cargo run --bin snd-dice-ctl-service 1 
type=PATH msg=audit(20/07/22 15:23:37.098:305) : item=1 name=/home/id/.cargo/bin/rustup-init inode=13293144 dev=08:42 mode=file,775 ouid=id ogid=id rdev=00:00 nametype=DELETE cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=PATH msg=audit(20/07/22 15:23:37.098:305) : item=0 name=/home/id/.cargo/bin/ inode=13247264 dev=08:42 mode=dir,775 ouid=id ogid=id rdev=00:00 nametype=PARENT cap_fp=none cap_fi=none cap_fe=0 cap_fver=0 cap_frootid=0 
type=CWD msg=audit(20/07/22 15:23:37.098:305) : cwd=/home/id/.builds/firewire/snd-firewire-ctl-services 
type=SYSCALL msg=audit(20/07/22 15:23:37.098:305) : arch=x86_64 syscall=unlink success=yes exit=0 a0=0x55b28d748e20 a1=0x20 a2=0x20 a3=0xfff items=2 ppid=12639 pid=1635287 auid=id uid=id gid=id euid=id suid=id fsuid=id egid=id sgid=id fsgid=id tty=(none) ses=5 comm=cargo exe=/home/id/.cargo/bin/cargo subj==unconfined key=(null) 
θ60° [id:~] $ 
```

and here was the error message complain from the side of rustup:

```sh
[id:~/.builds/swhkd] main ± rustup self update
info: checking for self-updates
info: downloading self-update
error: failed to set permissions for '/home/id/.cargo/bin/rustup-init': No such file or directory (os error 2)
```

so when i changed my systemd service file (for your service snd-firewire-ctl-*), i removed the `cargo run`... and just invoked the executable directly. From a static known folder. And the issue went away.

I think this is a bad thing, no idea why it happens. Perhaps it should be reported upstream (to rust developers somewhere). Also maybe remove `cargo run` from your readme file. Unless / until it can be fixed properly upstream.

Many thanks!

**Comment by takaswie** [comment]
Hi @dreamcat4 ,

Sorry to be late for reply. I think that addition of installation instruction will help you.

Today I pushed [topic/services/move-binaries](https://github.com/alsa-project/snd-firewire-ctl-services/tree/topic/services/move-binaries) with README updates after directory layout change. Would I ask you to read the installation/uninstallation instruction?

Thanks

**Comment by dreamcat4** [comment]
@takaswie looks OK to me. just there is a small typo now in the README here:

> When installing, the executable is usually put under `~/,cargo/bin` without any extra settings.

should be:

`~/.cargo/bin`

**Comment by takaswie** [comment]
> @takaswie looks OK to me. just there is a small typo now in the README here:
> 
> > When installing, the executable is usually put under `~/,cargo/bin` without any extra settings.
> 
> should be:
> 
> `~/.cargo/bin`

Oops. I force-pushed with fix to it, then merge to main.

I think the issue does not appear when execute the installed binary. If it satisfies, please close the issue. Else, please report new issue blocker.

Thanks
