### ISSUE TITLE
Fireface 802 : does not work with a buffer size of 128 / periods 2

### ISSUE THREAD

**Issue by francoisromain** [alsa-project/snd-firewire-ctl-services#94]
Hello 

The driver works well with the fireface 802 with a buffer size of 256 or 64 and Periods = 2,
but there is an error when the buffer size = 128, and periods = 2. 

Here are the error logs:

```
Starting jack server...
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Acquired audio card Audio5
creating alsa driver ... hw:Fireface802,0|hw:Fireface802,0|128|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 128 frames (2.7 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ERROR: ALSA: cannot set hardware parameters for capture
ERROR: ALSA: cannot configure capture channel
Released audio card Audio5
ERROR: Cannot initialize driver
ERROR: JackServer::Open failed with -1
ERROR: Failed to open server
```
This works fine when the buffer size = 128, and periods = 4.

**Comment by takaswie** [comment]
Hi,

Thanks for your reporting the issue, however ALSA fireface driver is under development and
we have many variations depending on kernel version.

Would I request you to report which version of the driver you use? For example, it's preferable to report
the kernel version.

**Comment by takaswie** [comment]
And let me transfer the issue to the repository which I use for driver maintenance..

**Comment by takaswie** [comment]
Hmm. The service of github.com dowsn't allow to transfer issues to the other project crossed namespace (from alsa-project to my private).

Would I ask you file the issue to https://github.com/takaswie/snd-firewire-improve/issues and close the previous one?

Regards

**Comment by francoisromain** [comment]
Sorry for my late reply. I was off the computer for a few days. 

Here is the updated issue : https://github.com/takaswie/snd-firewire-improve/issues/46

Thank you
