### ISSUE TITLE
oxfw (Apogee Duet FW): "Configuration ROM is not for 1394TA standard"

### ISSUE THREAD

**Issue by loquesangra** [alsa-project/snd-firewire-ctl-services#96]
Hello,

I get the following error while trying to start the driver for the Apogee Duet audio interface. JACK has been working well with it.
```
$ cargo run --bin snd-oxfw-ctl-service 2
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/snd-oxfw-ctl-service 2`
Linux file operation error: , Configuration ROM is not for 1394TA standard

Usage:
  snd-oxfw-ctl-service CARD_ID

  where
    CARD_ID: The numeric ID of sound card
```

**Comment by takaswie** [comment]
Hi,

Thanks for your reporting the issue. In recent weeks I merged many changes into master branch,
thus I'd like you to ask which points of history you use for your test. It's preferable to report the
commit hash of HEAD in your local repository.

Thanks

**Comment by takaswie** [comment]
Hi @loquesangra 

I filed #97 to fix the issue. Would I ask you to test the fix in your environment?

Thanks

**Comment by takaswie** [comment]
The PR branch is not merged into master branch.

**Comment by loquesangra** [comment]
@takaswie It is working now :-)
http://ttm.sh/wm1.png

**Comment by takaswie** [comment]
> The PR branch is not merged into master branch.

Oops. I mistook to write it. The branch was already merged...

> It is working now :-)

Great ;)

Thanks
